### ISSUE TITLE
DSA 2.2.9 Searching & Sorting Algorithms : Merge Sort - Video

### ISSUE THREAD

**Issue by goelesha** [girlscript/winter-of-contributing#3306]
### Description
Implement and explain Merge sort Algorithm

## Task
- [ ] Video

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- **Mention the type of contribution you want to make**.
- Kindly refer to the [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- **Do not use the assign command for this issue. Follow the above procedure.**
- In case you see that the issue has already been assigned, try to request a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be the same as the issue.
- This issue is only for 'GWOC' contributors of the 'DSA' Domain.

### Domain

DSA

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### Domain

DSA

### Type of Contribution

Audio

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### Domain

DSA

### Type of Contribution

Video

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by HassanRahim26** [comment]
Hey @goelesha, I would like to work on this issue. Can you please assign me this issue.
Name: Hassan Rahim
Batch: DSA Batch-2
Type: Documentation

**Comment by HassanRahim26** [comment]
Hey @goelesha, I would like to work on this issue. Can you please assign me this issue.
Name: Hassan Rahim
Batch: DSA Batch-2
Type: Documentation

**Comment by HassanRahim26** [comment]
Hey @goelesha, I would like to work on this issue. Can you please assign me this issue.
Name: Hassan Rahim
Batch: DSA Batch-2
Type: Documentation

**Comment by goelesha** [comment]
> Hey @goelesha, I would like to work on this issue. Can you please assign me this issue.
> Name: Hassan Rahim
> Batch: DSA Batch-2
> Type: Documentation

@HassanRahim26 Pls read the title of the issue carefully. This issue is for a video on merge sort.

**Comment by HassanRahim26** [comment]
@goelesha, is there any issue related to Merge Sort which you have opened in which, we have to contribute in Documentation form.

**Comment by goelesha** [comment]
@HassanRahim26 It is already assigned

**Comment by uzma024** [comment]
Hey @goelesha, I would love to contribute to this issue. Can you please assign me this issue.
Name: Uzma Firoz Khan
Batch: DSA Batch-10
Type: Video

**Comment by uzma024** [comment]
Also,I just selected documentation in the form submitted during enrolment . Is it okay if I switch to video?

**Comment by goelesha** [comment]
@uzma024 Assigning the issue to you for video. Make sure to submit a PR within 7 days.

I can't really comment about the things you have selected during enrollment or how exactly contributions will be counted. You can confirm with the GWOC team.

**Comment by uzma024** [comment]
Yeah I've confirmed. Thanks for assigning.

**Comment by purohitmansi** [comment]
Please do assign this to me.

**Comment by uzma024** [comment]
@goelesha I've made the video and upload it on google drive with some resources. I am not able to upload video on YouTube. Should add the g drive link instead, for the PR?
