### ISSUE TITLE
DSA 3.1.2.3 LINKED LIST- Operations on Linked List - Searching

### ISSUE THREAD

**Issue by goelesha** [girlscript/winter-of-contributing#5507]
### Description
Explain and implement searching in the linked list.

**Do not use ASSIGN command**

## Task
- [ ] Documentation

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- **Mention the type of contribution you want to make**.
- Kindly refer to the [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- **Do not use the assign command for this issue. Follow the above procedure.**
- In case you see that the issue has already been assigned, try to request a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be the same as the issue.
- This issue is only for 'GWOC' contributors of the 'DSA' Domain.

### Domain

DSA

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### Domain

DSA

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### Domain

DSA

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### Domain

DSA

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by chetan-2002** [comment]
Chetan Thakral
Batch -10 
I am very much excited to work upon this issue and I would like to contribute to the **documentation** part.  Can you please assign this issue to me?

**Comment by pranshukas** [comment]
@goelesha I would be happy to work on this weeks issues. You can assign me the task.
Name: Pranshu Kashyap 
Batch : DSA Batch 5
Type of Contribution: Documentation

**Comment by goelesha** [comment]
@chetan-2002 Assigning it to you. 
@adityaraj079 It has been mentioned that don't use the assign command on issues created by supervisors. Look for some other issue to work on. You can work on audio or video of this topic if interested.

**Comment by goelesha** [comment]
@Anushka-Gamad Assigning it you for audio.
